- name: Configure web servers
  hosts: web
  become: true
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Create directory structure for web documents
      file:
        path: "/web/html"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Copy nginx conf file to server
      copy:
        src: ./files/nginx.conf
        dest: /etc/nginx/sites-available/default
        owner: root
        group: root
        mode: '0644'

    - name: Create a link to nginx config file to enable it
      ansible.builtin.file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link

    - name: Generate index.html file from template
      template:
        src: ./templates/index.html.j2
        dest: /web/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Reload nginx service
      ansible.builtin.service:
        name: nginx
        state: reloaded
        enabled: yes
